### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by benc-uk** [aztfmod/rovergo#53]
Unit tests are the wild new craze taking the software development world by storm.

We should get on this new hotness and some of these so called "unit tests" to rover v2

To be agreed:
- Can we really unit test without azure/backend changes?
- Where to focus the tests?

**Comment by sebastus** [comment]
Here's a conference video on the topic of "unit testing" [here](https://terratest.gruntwork.io/docs/getting-started/introduction/). He says that with infra code, "unit testing" is really not. Because 99% of what infra code does is work with the outside world (Azure), if you try to isolate that, there's nothing to do. Then he goes on to show how Terratest works.

**Comment by sebastus** [comment]
I added a single unit test as a pattern for more. It creates a cobra command, adds the needed command line parameters, then does a BuildOptions. Assertions on the Options struct that gets created are the test. Tests can be extended easily to become integration tests by tweaking the last 4 lines of the test code - just reference the actual Action rather than the mock action.
